<!DOCTYPE html>
<title>Canvas test: 2d.imageData.create1.zero</title>
<script src="../tests.js"></script>
<link rel="stylesheet" href="../tests.css">
<link rel="prev" href="2d.imageData.create2.nonfinite.html" title="2d.imageData.create2.nonfinite">
<link rel="next" href="2d.imageData.create2.round.html" title="2d.imageData.create2.round">
<body class="show_output">
<p>
 <a href="2d.imageData.create2.nonfinite.html" accesskey="p" title="[p] 2d.imageData.create2.nonfinite">&lt;</a>
 <a href="index.html">[index]</a>
 <a href="2d.imageData.create2.round.html" accesskey="n" title="[n] 2d.imageData.create2.round">&gt;</a>
<h1><a href="index.2d.html">2d</a>.<a href="index.2d.imageData.html">imageData</a>.<a href="index.2d.imageData.create1.html">create1</a>.zero</h1>
<p class="desc">createImageData(null) throws INDEX_SIZE_ERR</p>
<div class="refs">References:
<ul>
<li><a href="spec.html#testrefs.2d.imageData.create.null">2d.imageData.create.null</a>

</ul>
</div>

<p class="output">Actual output:</p>
<canvas id="c" class="output" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>

<ul id="d"></ul>
<script>
_addTest(function(canvas, ctx) {

try { var _thrown = false;
  ctx.createImageData(null);
} catch (e) { if (e.code != DOMException.NOT_SUPPORTED_ERR) _fail("Failed assertion: expected exception of type NOT_SUPPORTED_ERR, got: "+e.message); _thrown = true; } finally { _assert(_thrown, "should throw exception of type NOT_SUPPORTED_ERR: ctx.createImageData(null)"); }


});
</script>

