<!DOCTYPE html>
<title>Canvas test: 2d.imageData.create2.zero</title>
<script src="../tests.js"></script>
<link rel="stylesheet" href="../tests.css">
<link rel="prev" href="2d.imageData.create2.negative.html" title="2d.imageData.create2.negative">
<link rel="next" href="2d.imageData.create2.nonfinite.html" title="2d.imageData.create2.nonfinite">
<body class="show_output">
<p>
 <a href="2d.imageData.create2.negative.html" accesskey="p" title="[p] 2d.imageData.create2.negative">&lt;</a>
 <a href="index.html">[index]</a>
 <a href="2d.imageData.create2.nonfinite.html" accesskey="n" title="[n] 2d.imageData.create2.nonfinite">&gt;</a>
<h1><a href="index.2d.html">2d</a>.<a href="index.2d.imageData.html">imageData</a>.<a href="index.2d.imageData.create2.html">create2</a>.zero</h1>
<p class="desc">createImageData(sw, sh) throws INDEX_SIZE_ERR if size is zero</p>
<div class="refs">References:
<ul>
<li><a href="spec.html#testrefs.2d.imageData.getcreate.zero">2d.imageData.getcreate.zero</a>
<li><a href="https://bugzilla.mozilla.org/show_bug.cgi?id=433004">Bugzilla</a>
</ul>
</div>

<p class="output">Actual output:</p>
<canvas id="c" class="output" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>

<ul id="d"></ul>
<script>
_addTest(function(canvas, ctx) {

try { var _thrown = false;
  ctx.createImageData(10, 0);
} catch (e) { if (e.code != DOMException.INDEX_SIZE_ERR) _fail("Failed assertion: expected exception of type INDEX_SIZE_ERR, got: "+e.message); _thrown = true; } finally { _assert(_thrown, "should throw exception of type INDEX_SIZE_ERR: ctx.createImageData(10, 0)"); }
try { var _thrown = false;
  ctx.createImageData(0, 10);
} catch (e) { if (e.code != DOMException.INDEX_SIZE_ERR) _fail("Failed assertion: expected exception of type INDEX_SIZE_ERR, got: "+e.message); _thrown = true; } finally { _assert(_thrown, "should throw exception of type INDEX_SIZE_ERR: ctx.createImageData(0, 10)"); }
try { var _thrown = false;
  ctx.createImageData(0, 0);
} catch (e) { if (e.code != DOMException.INDEX_SIZE_ERR) _fail("Failed assertion: expected exception of type INDEX_SIZE_ERR, got: "+e.message); _thrown = true; } finally { _assert(_thrown, "should throw exception of type INDEX_SIZE_ERR: ctx.createImageData(0, 0)"); }


});
</script>

