<!DOCTYPE html>
<title>Canvas test: 2d.pattern.repeat.case</title>
<script src="../tests.js"></script>
<link rel="stylesheet" href="../tests.css">
<link rel="prev" href="2d.pattern.repeat.unrecognised.html" title="2d.pattern.repeat.unrecognised">
<link rel="next" href="2d.pattern.repeat.nullsuffix.html" title="2d.pattern.repeat.nullsuffix">
<body class="show_output">
<p>
 <a href="2d.pattern.repeat.unrecognised.html" accesskey="p" title="[p] 2d.pattern.repeat.unrecognised">&lt;</a>
 <a href="index.html">[index]</a>
 <a href="2d.pattern.repeat.nullsuffix.html" accesskey="n" title="[n] 2d.pattern.repeat.nullsuffix">&gt;</a>
<h1><a href="index.2d.html">2d</a>.<a href="index.2d.pattern.html">pattern</a>.<a href="index.2d.pattern.repeat.html">repeat</a>.case</h1>
<p class="desc"></p>
<div class="refs">References:
<ul>
<li><a href="spec.html#testrefs.2d.pattern.exact">2d.pattern.exact</a>

</ul>
</div>

<p class="output">Actual output:</p>
<canvas id="c" class="output" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>

<ul id="d"></ul>
<script>
_addTest(function(canvas, ctx) {

try { var _thrown = false;
  ctx.createPattern(canvas, "Repeat");
} catch (e) { if (e.code != DOMException.SYNTAX_ERR) _fail("Failed assertion: expected exception of type SYNTAX_ERR, got: "+e.message); _thrown = true; } finally { _assert(_thrown, "should throw exception of type SYNTAX_ERR: ctx.createPattern(canvas, \"Repeat\")"); }


});
</script>

